#!/usr/bin/env bash
#Bash script prints "Best school"  10 times and "Hi" on the 9th iteration

number=1
while [ $number -le 10 ]
do
	echo "Best School"
	if [ $number == 9 ]
	then
		echo "Hi"
	fi
	number=$(( number+1 ))
done
